spring.application.name=room-api

spring.datasource.url=jdbc:mysql://localhost:3306/roomdb
spring.datasource.username=roomapp
spring.datasource.password=roomapp1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
